apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  type: Opaque
data:
  BROKER_PASSWORD: {{ .Values.rabbitmq.password| b64enc }}
  DB_PASSWORD: {{ .Values.rds.host| b64enc }}